# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'RxSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftTest
  pod 'RxCocoa'
  pod 'RxSwift'
  target 'RxSwiftTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftTestUITests' do
    # Pods for testing
  end

end
